Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-0852de09092f3a061
    Description: AMI ID for the EC2 instance

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair

  # Remove this parameter since we'll define the security group within the template
  # SecurityGroupId:
  #   Type: AWS::EC2::SecurityGroup::Id
  #   Description: Security Group ID for the EC2 instances

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID for the EC2 instances

  VPCId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID where the instances will be launched

  DesiredCapacity:
    Type: Number
    Default: 2
    Description: Number of instances to launch in the Auto Scaling Group

Resources:
  TrainingNodeRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess  # Adjust as necessary
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess  # Consider creating a custom policy for least privilege

  TrainingNodeInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref TrainingNodeRole

  TrainingNodeSSMPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: TrainingNodeSSMPolicy
      Roles:
        - !Ref TrainingNodeRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:GetParameter
            Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/distributed-training/*"

  TrainingSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and DDP communication
      VpcId: !Ref VPCId
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  SSHIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref TrainingSecurityGroup
      IpProtocol: tcp
      FromPort: 22
      ToPort: 22
      CidrIp: 0.0.0.0/0  # Replace with your IP range for SSH access

  DDPIngressRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      GroupId: !Ref TrainingSecurityGroup
      IpProtocol: tcp
      FromPort: 29500
      ToPort: 29500
      SourceSecurityGroupId: !Ref TrainingSecurityGroup

  TrainingNodeLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: TrainingNodeLaunchTemplate
      LaunchTemplateData:
        InstanceType: g4dn.xlarge
        ImageId: !Ref ImageId
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref TrainingSecurityGroup
        IamInstanceProfile:
          Arn: !GetAtt TrainingNodeInstanceProfile.Arn
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e
            cd /home/ubuntu
            # Install Poetry
            curl -sSL https://install.python-poetry.org | python3 -
            # Update PATH for the current session
            export PATH="/home/ubuntu/.local/bin:$PATH"
            echo 'export PATH="/home/ubuntu/.local/bin:$PATH"' >> /home/ubuntu/.bashrc
            # Clone your repository
            git clone https://github.com/ghudeihed/DDPTraining.git
            cd DDPTraining
            # Install dependencies using Poetry
            poetry install
            # Activate the Poetry environment
            source $(poetry env info --path)/bin/activate
            # Distributed training configuration
            export WORLD_SIZE=${DesiredCapacity}
            export RANK=$(curl -s http://169.254.169.254/latest/meta-data/ami-launch-index)
            export PRIVATE_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
            export MASTER_PORT=29500
            if [ "$RANK" -eq "0" ]; then
              # Master node writes its IP to SSM Parameter Store
              aws ssm put-parameter --name "/distributed-training/master-ip" --type "String" --value "$PRIVATE_IP" --overwrite --region ${AWS::Region}
              export MASTER_ADDR="$PRIVATE_IP"
            else
              # Wait for the master IP to be available
              until [ -n "$MASTER_ADDR" ]; do
                MASTER_ADDR=$(aws ssm get-parameter --name "/distributed-training/master-ip" --query "Parameter.Value" --output text --region ${AWS::Region} || echo "")
                sleep 5
              done
              export MASTER_ADDR
            fi
            # Run your training script
            nohup poetry run python train.py > /home/ubuntu/train.log 2>&1 &

  TrainingNodeAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: TrainingNodeASG
      VPCZoneIdentifier:
        - !Ref SubnetId
      LaunchTemplate:
        LaunchTemplateId: !Ref TrainingNodeLaunchTemplate
        Version: !GetAtt TrainingNodeLaunchTemplate.LatestVersionNumber
      MinSize: '1'
      MaxSize: '10'
      DesiredCapacity: !Ref DesiredCapacity
      Tags:
        - Key: Name
          Value: TrainingNode
          PropagateAtLaunch: true
        - Key: Project
          Value: DDPTraining
          PropagateAtLaunch: true
